In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [3]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])
print ("Adding 1 to every element:", a + 1)
print ("\nSubtracting 2 from each element:", b - 2)
print ("\nSum of all array "
       "elements: ", a.sum())
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [4]:
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)         
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int64

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [5]:
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements: 
19.0

Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array: 
[[4. 2.]
 [7. 6.]]


In [6]:
arr = np.array(["qiam", "hasan", "suleman","hasan"])
print(arr,"\n",arr.dtype)
print(type(arr))
arr0 = np.array(["we", "are","hasan"])
print(arr0,"\n",arr0.dtype)
print(type(arr0))

['qiam' 'hasan' 'suleman' 'hasan'] 
 <U7
<class 'numpy.ndarray'>
['we' 'are' 'hasan'] 
 <U5
<class 'numpy.ndarray'>


In [7]:
arr1=np.array([1,2,3,4,5])
print(arr1,"\n",arr1.dtype)
print(type(arr1))
arr4=np.array([1,2,3,4,5],dtype="int32")
print(arr4,"\n",arr4.dtype)
print(type(arr4))
arr2=np.array([1.0,2.0,3.0,4.0])
print(arr2,"\n",arr2.dtype)
print(type(arr2))
arr3=np.array([1.0,2.0,3.0,4.0],dtype="int32")
print(arr3,"\n",arr3.dtype)
print(type(arr3))


[1 2 3 4 5] 
 int64
<class 'numpy.ndarray'>
[1 2 3 4 5] 
 int32
<class 'numpy.ndarray'>
[1. 2. 3. 4.] 
 float64
<class 'numpy.ndarray'>
[1 2 3 4] 
 int32
<class 'numpy.ndarray'>


In [8]:
c=np.array([1,2.0,3.0,6,5,3.0])
print(c,"\n",c.dtype)
print(c.astype(bool))

[1. 2. 3. 6. 5. 3.] 
 float64
[ True  True  True  True  True  True]


In [13]:
d=np.array([1,2,3,4,5])
e=d.view()
e[0]=99
s=d.copy()
s[0]=88
print(d)
print(e)
print(s)
print(d)
print(d.base)
print(e.base)
print(s.base)
print(d.base)

[99  2  3  4  5]
[99  2  3  4  5]
[88  2  3  4  5]
[99  2  3  4  5]
None
[99  2  3  4  5]
None
None


In [26]:
cpy=np.array(["qaim","yasir","hasan"])
cp1=cpy
print(cp1)
print(cp1)
f=np.array([[[2,3],[3,4]],
            [[5,6],[8,9]]])
l=np.array([[[2,3]],
            [[5,6]]])
g=np.array([[[2,3,4]],
            [[5,6,4]]])
print(g)
print(g.shape)
print(l)
print(l.shape)
print(f)
print(f.shape)

['qaim' 'yasir' 'hasan']
['qaim' 'yasir' 'hasan']
[[[2 3 4]]

 [[5 6 4]]]
(2, 1, 3)
[[[2 3]]

 [[5 6]]]
(2, 1, 2)
[[[2 3]
  [3 4]]

 [[5 6]
  [8 9]]]
(2, 2, 2)


In [36]:
mat=np.array([1,2,3,4,5,6,67,8,9])
mat1=np.array([1,2,3,4,5,6,67,8,9,2,5,1])
print(mat1)
print(mat1.ndim)
print(mat1.reshape(4,3))
print(mat1.reshape(4,3).ndim)
print(mat)
print(mat.ndim)
print(mat.reshape(3,3))
print(mat.reshape(3,3).ndim)

[ 1  2  3  4  5  6 67  8  9  2  5  1]
1
[[ 1  2  3]
 [ 4  5  6]
 [67  8  9]
 [ 2  5  1]]
2
[ 1  2  3  4  5  6 67  8  9]
1
[[ 1  2  3]
 [ 4  5  6]
 [67  8  9]]
2


In [38]:
m=s.reshape(2,2,2)
d=q.reshape(-1)
print(d)
print(d.ndim)

ValueError: cannot reshape array of size 5 into shape (2,2,2)

In [68]:
a=range(100)
num=np.array([a])
print(num)
c=num.reshape(5,5,4)
print(c)
print(num*2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]
  [72 73 74 75]
  [76 77 78 79]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]
[[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
   36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
   72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
  108 110 112 114 116 118 120 122 124 126 128 130 132 13