In [2]:
for x in range(0,5):
    for j in range(0,x+1):
        print("*",end="")
    print("\r")    

*
**
***
****
*****


In [3]:
for x in range(0,5):
        print("*",end="")

*****

In [4]:
for x in range(0,5):
        print("*")

*
*
*
*
*


In [5]:
J=0
for j in range(5):
    print("* * * * *")
    j=j+1

* * * * *
* * * * *
* * * * *
* * * * *
* * * * *


In [6]:
for i in reversed(range(0,5)):
    for n in range(0,i+1):
        print("*",end="")
    print("")   

*****
****
***
**
*


In [7]:
import numpy as np

In [8]:
g=np.array([1,2,3,4,5,6,7,8,9,10])
print(g)
h=np.split(g,5)
print(h[0])
print(h[1])
print(h[2])
print(h[3])
print(h)
f=np.array_split(g,8)
print(f)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2]
[3 4]
[5 6]
[7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([10])]


In [9]:
e=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
print(e)
d=np.array_split(e,2)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]


In [10]:
e=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
print(e)
d=np.array_split(e,2,axis=1)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[array([[1, 2, 3],
       [6, 7, 8]]), array([[ 4,  5],
       [ 9, 10]])]


In [17]:
arr=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,17]]]])
print(arr)
s=np.array_split(arr,4)
print(s[2])

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 17]]]]
[]
